### ISSUE TITLE
Sprint 3 Plan

### ISSUE THREAD

**Issue by MatJackson** [MatJackson/SD2#23]

**Comment by nattganesh** [comment]
- [ ] Notifications -------Issue #13

- [ ] Send and receive private messages -------Issue #15

- [ ] Ability to search for questions -------Issue #12 

- [ ] Profile Page -------Issue #10 

- [ ] Ability to apply Voting System to Mulitple Users -------Issue #35 

- [ ] Ability to reply to comments AND edit/delete comment

**Comment by MatJackson** [comment]
when user registers, automatically log in

**Comment by Zhen-Yee** [comment]
add font size, italic, bold to post
display user avatar on post
